spring.application.name=employee-management-system
server.port=8080


spring.datasource.url=jdbc:mariadb://localhost:3306/databaze
spring.datasource.username=root
spring.datasource.password=Hellbound_6
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

